name: CI

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run package-firefox
        if: contains(github.ref, "release")
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - run: npm run package-chrome
        if: contains(github.ref, "release")
      - uses: djnicholson/release-action@v2.11
        if: contains(github.ref, "release")
        with:
          token: ${{ secrets.GH_TOKEN }}
          asset-name: 'firefox.xpi'
          file: 'web-ext-artifacts/firefox.xpi'
      - uses: djnicholson/release-action@v2.11
        if: contains(github.ref, "release")
        with:
          token: ${{ secrets.GH_TOKEN }}
          asset-name: 'chrome.zip'
          file: 'chrome.zip'

