name: CI

on:
  push:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
      - run: npm run build

# TODO: 
# * https://github.com/marketplace/actions/github-release
# - if [ "$TRAVIS_TAG" != '' ]; then npm run package-firefox; fi
# - if [ "$TRAVIS_TAG" != '' ]; then npm run package-chrome; fi
# file:
#    - ./web-ext-artifacts/firefox.xpi
#    - chrome.zip
